import { StyleSheet } from 'react-native';
import { accent, accentBorder, accentFaint, accentGlow, accentSoft, bg, faint, headerBg, line, muted, panel, panelSoft, sidebarBg, surfaceElevated, text } from './theme';

export const styles = StyleSheet.create({
  safe: { backgroundColor: bg, flex: 1 },
  stage: {
    alignItems: 'center',
    backgroundColor: bg,
    flex: 1,
    justifyContent: 'flex-start',
    minHeight: 0,
    paddingHorizontal: 0,
  },
  desktopStage: {
    alignItems: 'center',
    backgroundColor: bg,
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  frame: {
    backgroundColor: panel,
    flex: 1,
    maxHeight: '100%',
    maxWidth: 480,
    overflow: 'hidden',
    width: '100%',
  },
  desktopFrame: {
    alignItems: 'center',
    backgroundColor: bg,
    justifyContent: 'center',
    maxWidth: '100%',
  },
  desktopShell: {
    backgroundColor: panel,
    flexDirection: 'row',
    height: '100%',
    maxHeight: '100%',
    minHeight: 0,
    overflow: 'hidden',
    width: '100%',
  },
  desktopShellCollapsed: {},
  desktopSidebar: {
    backgroundColor: sidebarBg,
    borderRightColor: line,
    borderRightWidth: 1,
    gap: 16,
    paddingHorizontal: 14,
    paddingTop: 20,
    width: 210,
  },
  desktopSidebarCollapsed: {
    alignItems: 'center',
    paddingHorizontal: 8,
    width: 72,
  },
  desktopSidebarHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
    paddingBottom: 10,
  },
  desktopLogoGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  desktopLogoGroupCollapsed: {
    justifyContent: 'center',
    width: 32,
  },
  desktopLogoMark: {
    height: 22,
    position: 'relative',
    width: 22,
  },
  desktopLogoMarkBlade: {
    backgroundColor: accent,
    borderRadius: 4,
    height: 9,
    left: 2,
    position: 'absolute',
    top: 6,
    width: 18,
  },
  desktopLogoMarkBladeOne: {
    transform: [{ rotate: '-42deg' }],
  },
  desktopLogoMarkBladeTwo: {
    opacity: 0.72,
    transform: [{ rotate: '42deg' }],
  },
  kodaMarkIcon: {
    position: 'relative',
  },
  kodaMarkIconBlade: {
    backgroundColor: accent,
    opacity: 0.72,
    position: 'absolute',
    transform: [{ rotate: '-45deg' }],
  },
  kodaMarkIconBladeBack: {
    opacity: 0.78,
    transform: [{ rotate: '45deg' }],
  },
  kodaMarkIconBladeActive: {
    backgroundColor: accent,
    opacity: 1,
  },
  desktopLogoWord: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
  },
  desktopLogoCollapsed: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
    width: '100%',
  },
  desktopSidebarToggle: {
    alignItems: 'center',
    borderColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  desktopNavList: {
    gap: 7,
  },
  desktopNavDivider: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    height: 1,
    marginBottom: 7,
    marginTop: 8,
    width: '100%',
  },
  desktopNavItem: {
    alignItems: 'center',
    borderColor: 'transparent',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 39,
    paddingHorizontal: 12,
  },
  desktopNavItemActive: {
    backgroundColor: accentSoft,
    borderColor: accent,
    borderWidth: 1,
    boxShadow: `inset 0 0 18px ${accentFaint}`,
  },
  desktopNavItemFeatured: {
    marginVertical: 3,
  },
  desktopNavItemCollapsed: {
    height: 38,
    justifyContent: 'center',
    paddingHorizontal: 0,
    width: 42,
  },
  desktopNavIcon: {
    alignItems: 'center',
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  desktopNavText: {
    color: '#a4a5a4',
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  desktopNavTextActive: {
    color: accent,
    fontWeight: '700',
  },
  desktopSidebarFooter: {
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    borderTopWidth: 1,
    marginTop: 'auto',
    paddingBottom: 16,
    paddingTop: 13,
  },
  desktopSidebarStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  desktopSidebarStatusCollapsed: {
    justifyContent: 'center',
  },
  desktopSidebarUtilityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  desktopSidebarUtilityRowCollapsed: {
    flexDirection: 'column',
  },
  desktopCollapseTextButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 30,
  },
  desktopCollapseText: {
    color: muted,
    fontSize: 10,
  },
  desktopPageHost: {
    backgroundColor: bg,
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  desktopThreeColumnPage: { flex: 1, flexDirection: 'row', gap: 24, minHeight: 0, minWidth: 0, width: '100%' },
  desktopMainColumn: { flex: 1, minHeight: 0, minWidth: 0 },
  desktopRightColumn: { borderLeftColor: line, borderLeftWidth: 1, flexShrink: 0, minHeight: 0, paddingLeft: 20, width: 330 },
  desktopColumnScroll: { gap: 14, paddingBottom: 32 },
  progressDesktopMainFlow: { gap: 14 },
  desktopTopBar: {
    alignItems: 'center',
    backgroundColor: headerBg,
    borderBottomColor: line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 46,
  },
  desktopTopBarInner: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 36,
    width: '100%',
  },
  desktopTitleGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  desktopBrand: {
    color: accent,
    fontSize: 11,
    letterSpacing: 7,
    opacity: 0.88,
  },
  desktopActiveTitle: {
    color: text,
    fontSize: 13,
    fontWeight: '600',
  },
  desktopTopActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  desktopSyncPill: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginRight: 8,
  },
  desktopSyncText: {
    color: muted,
    fontSize: 10,
  },
  desktopIconButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  desktopUserBubble: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  desktopWorkspace: {
    alignItems: 'stretch',
    alignSelf: 'center',
    backgroundColor: panel,
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    maxWidth: 1360,
    width: '100%',
    paddingHorizontal: 28,
    paddingTop: 28,
  },
  desktopContentGrid: {
    alignItems: 'flex-start',
    flex: 1,
    flexDirection: 'row',
    gap: 20,
    maxWidth: 1360,
    minHeight: 0,
    width: '100%',
  },
  desktopContentGridSingle: {
    maxWidth: 900,
  },
  desktopContent: {
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  desktopScreenScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    width: '100%',
  },
  desktopPageScroll: {
    flexGrow: 1,
    gap: 14,
    paddingBottom: 28,
    width: '100%',
  },
  desktopAside: {
    alignSelf: 'flex-start',
    borderLeftColor: line,
    borderLeftWidth: 1,
    gap: 12,
    flexShrink: 0,
    paddingLeft: 20,
    width: 330,
  },
  desktopAsideCard: {
    backgroundColor: surfaceElevated,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 16px 36px rgba(0, 0, 0, 0.22)',
    gap: 10,
    padding: 14,
  },
  desktopAsideTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  desktopAsideRow: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  desktopAsideRowText: {
    color: muted,
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  desktopAsideMeta: {
    color: muted,
    fontSize: 11,
    lineHeight: 16,
  },
  desktopFocusRow: {
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    justifyContent: 'center',
  },
  desktopFocusRing: {
    alignItems: 'center',
    borderColor: accent,
    borderRadius: 999,
    backgroundColor: accentFaint,
    borderWidth: 6,
    boxShadow: `0 0 42px ${accentGlow}`,
    height: 96,
    justifyContent: 'center',
    width: 96,
  },
  desktopFocusNumber: {
    color: text,
    fontSize: 28,
    fontWeight: '300',
    lineHeight: 34,
  },
  desktopProgressRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  desktopProgressPercent: {
    color: text,
    fontSize: 24,
    fontWeight: '300',
    lineHeight: 30,
    width: 48,
  },
  desktopProgressTrack: {
    backgroundColor: '#303130',
    borderRadius: 999,
    flex: 1,
    height: 8,
    overflow: 'hidden',
  },
  desktopProgressFill: {
    backgroundColor: accent,
    height: '100%',
  },
  desktopMiniCalendar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  desktopMiniCalendarText: {
    color: muted,
    fontSize: 10,
    lineHeight: 18,
    textAlign: 'center',
    width: 28,
  },
  desktopMiniCalendarActive: {
    backgroundColor: accent,
    borderRadius: 999,
    color: panel,
    fontWeight: '700',
  },
  desktopStatRow: {
    borderBottomColor: '#202120',
    borderBottomWidth: 1,
    gap: 2,
    paddingBottom: 9,
  },
  desktopStatValue: {
    color: text,
    fontSize: 22,
    fontWeight: '300',
    lineHeight: 28,
  },
  desktopBigNumber: {
    color: text,
    fontSize: 44,
    fontWeight: '300',
    lineHeight: 52,
  },
  progressDesktopGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  progressDesktopMetrics: {
    flexBasis: 0,
    flexGrow: 0.8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    minWidth: 0,
  },
  progressDesktopMain: {
    flexBasis: 0,
    flexGrow: 1.2,
    gap: 12,
    minWidth: 0,
  },
  progressDesktopAside: {
    flexShrink: 0,
    gap: 12,
    width: 360,
  },
  progressChartPlaceholder: {
    alignItems: 'flex-end',
    borderBottomColor: line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    height: 110,
    paddingHorizontal: 8,
  },
  progressChartBar: {
    backgroundColor: accent,
    borderRadius: 999,
    opacity: 0.78,
    width: 18,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  headerLeft: { alignItems: 'center', flexDirection: 'row', gap: 12, minWidth: 0 },
  mobileMenuButton: { alignItems: 'center', height: 38, justifyContent: 'center', marginLeft: -8, width: 38 },
  headerSync: { alignItems: 'center', flexDirection: 'row', gap: 7, minWidth: 0 },
  logo: { color: accent, fontSize: 12, letterSpacing: 8 },
  syncStrip: { alignItems: 'center', flexDirection: 'row', gap: 7, paddingHorizontal: 16, paddingTop: 9 },
  syncStripDot: { backgroundColor: muted, borderRadius: 999, height: 7, width: 7 },
  syncStripDotOk: { backgroundColor: accent },
  syncStripDotOffline: { backgroundColor: '#ff4d4d' },
  syncStripText: { color: muted, fontSize: 10, lineHeight: 14 },
  content: { flex: 1, minHeight: 0, paddingHorizontal: 14, paddingTop: 14 },
  scrollContent: { gap: 10, paddingBottom: 24 },
  profileScrollContent: { gap: 12, paddingBottom: 30 },
  profileHeader: { gap: 6, marginBottom: 8 },
  profileTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  profileSignOutButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  profileAccountBox: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 74,
    padding: 12,
  },
  profileAccountMain: { flex: 1, gap: 3, minWidth: 0 },
  profileAccountName: { color: text, fontSize: 16, lineHeight: 21 },
  profileAccountSide: { alignItems: 'flex-end', gap: 7 },
  profileThemeBox: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  profileThemeTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  profileThemeList: { gap: 8 },
  profileThemeOption: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  profileThemeOptionActive: {
    backgroundColor: surfaceElevated,
    borderColor: accent,
  },
  profileThemeSwatches: { flexDirection: 'row', gap: 4 },
  profileThemeSwatch: {
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 18,
    width: 18,
  },
  profileThemeState: { color: muted, fontSize: 11, fontWeight: '700' },
  profileThemeStateActive: { color: accent },
  profilePasswordButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  profilePasswordButtonText: { color: accent, fontSize: 11, fontWeight: '700' },
  profileToast: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: panelSoft,
    borderColor: accentBorder,
    borderRadius: 999,
    borderWidth: 1,
    bottom: 86,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 16,
    position: 'absolute',
    zIndex: 60,
  },
  profileToastText: { color: accent, fontSize: 13, fontWeight: '700' },
  profileSettingsList: {
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  profileSettingRow: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderBottomColor: '#202120',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  profileSettingRowDisabled: { opacity: 0.52 },
  profileSettingText: { flex: 1, gap: 2, minWidth: 0 },
  profileSwitchTrack: {
    backgroundColor: '#252625',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 48,
  },
  profileSwitchTrackActive: { backgroundColor: accent },
  profileSwitchTrackDisabled: { backgroundColor: '#1a1b1a' },
  profileSwitchThumb: {
    backgroundColor: muted,
    borderRadius: 999,
    height: 22,
    width: 22,
  },
  profileSwitchThumbActive: { alignSelf: 'flex-end', backgroundColor: panel },
  profileDesktopLayout: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  profileDesktopMain: {
    flex: 1,
    gap: 12,
    minWidth: 0,
  },
  profileDesktopAside: {
    borderLeftColor: line,
    borderLeftWidth: 1,
    flexShrink: 0,
    gap: 12,
    paddingLeft: 20,
    width: 330,
  },
  titleBlock: { gap: 6, marginBottom: 8 },
  screenTitle: { color: text, fontSize: 22, fontWeight: '400', letterSpacing: 0 },
  subtitle: { color: muted, fontSize: 12, lineHeight: 18 },
  journalHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  journalHeaderActions: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 3 },
  journalHistoryButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 13,
  },
  journalHistoryText: { color: text, fontSize: 12 },
  journalAddButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    marginTop: 3,
    width: 34,
  },
  journalAddButtonDisabled: { opacity: 0.35 },
  journalBottomAddButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: accent,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 16,
  },
  journalBottomAddButtonDisabled: { opacity: 0.35 },
  journalBottomAddText: { color: panel, fontSize: 13, fontWeight: '700' },
  journalOptionalActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  journalDesktopLayout: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  journalDesktopMain: {
    flex: 1,
    gap: 14,
    minWidth: 0,
  },
  journalDesktopAside: { borderLeftColor: line, borderLeftWidth: 1, flexShrink: 0, gap: 10, paddingLeft: 20, width: 330 },
  journalDesktopHistoryList: { gap: 0 },
  journalDesktopHistoryRow: { borderBottomColor: line, borderBottomWidth: 1, gap: 4, minHeight: 62, paddingVertical: 10 },
  journalDesktopHistoryRowActive: { borderBottomColor: accent },
  desktopAsideHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 34 },
  journalHistoryDeleteButton: {
    alignItems: 'center',
    borderRadius: 999,
    flexShrink: 0,
    height: 26,
    justifyContent: 'center',
    marginLeft: 'auto',
    width: 26,
  },
  journalHistoryDeleteButtonHover: {
    backgroundColor: accentFaint,
  },
  journalReturnButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  journalReturnText: { color: accent, fontSize: 12, fontWeight: '700' },
  journalReadonlyArticle: {
    gap: 14,
    paddingTop: 4,
  },
  journalReadonlyText: {
    color: text,
    fontSize: 16,
    lineHeight: 25,
  },
  journalReadonlyMetaGrid: {
    gap: 18,
    paddingTop: 8,
  },
  journalReadonlyMetaSection: {
    gap: 10,
  },
  journalReadonlyMetaText: {
    color: muted,
    fontSize: 14,
    lineHeight: 20,
  },
  journalOptionButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 34,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  journalOptionText: { color: muted, fontSize: 12, lineHeight: 16 },
  card: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 9,
    padding: 13,
  },
  profileCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 9,
    minHeight: 112,
    padding: 13,
    width: '48.5%',
  },
  cardLabel: { color: muted, fontSize: 10, letterSpacing: 1.6 },
  cardText: { color: text, fontSize: 13, lineHeight: 19 },
  addBox: { borderColor: line, borderRadius: 7, borderWidth: 1, gap: 8, padding: 10 },
  addInput: { color: text, fontSize: 14, minHeight: 34 },
  addButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 4,
  },
  addButtonText: { color: accent, fontSize: 12 },
  list: { gap: 9 },
  taskRow: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 58,
    paddingHorizontal: 12,
  },
  checkCircle: {
    alignItems: 'center',
    borderColor: muted,
    borderRadius: 999,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  checkCircleDone: { backgroundColor: accent, borderColor: accent },
  rowText: { flex: 1, gap: 3 },
  rowTitle: { color: text, fontSize: 14, lineHeight: 20 },
  rowMeta: { color: muted, fontSize: 11, lineHeight: 16 },
  doneText: { color: muted, textDecorationLine: 'line-through' },
  rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  percentText: { color: text, fontSize: 12 },
  progressTrack: { backgroundColor: '#252625', height: 2, marginTop: 4, width: '100%' },
  progressFill: { backgroundColor: accent, height: 2 },
  plannerScreenRoot: { flex: 1, position: 'relative', width: '100%' },
  plannerDesktopRoot: {
    flex: 1,
    minHeight: 0,
    width: '100%',
  },
  plannerDesktopHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  plannerDesktopHeaderAddButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    boxShadow: `0 0 22px ${accentGlow}`,
    height: 44,
    justifyContent: 'center',
    marginTop: 4,
    width: 44,
  },
  plannerModeToggle: {
    alignSelf: 'flex-start',
    backgroundColor: '#151615',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 3,
    padding: 4,
  },
  plannerModeButton: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 14,
  },
  plannerModeButtonActive: { backgroundColor: accent },
  plannerModeText: { color: muted, fontSize: 12 },
  plannerModeTextActive: { color: panel, fontWeight: '700' },
  plannerDateBlock: { gap: 6 },
  plannerDesktopDateBlock: {
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    borderBottomColor: 'rgba(255, 255, 255, 0.10)',
    borderBottomWidth: 1,
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    maxWidth: '100%',
    minHeight: 54,
    paddingBottom: 9,
    paddingHorizontal: 0,
    paddingTop: 0,
    width: '100%',
  },
  plannerDesktopDayLayout: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  plannerDesktopMainColumn: {
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    gap: 12,
    minWidth: 0,
    width: 'auto',
  },
  plannerDateNavRow: { alignItems: 'stretch', flexDirection: 'row', gap: 8, maxWidth: 420 },
  plannerQuickDateRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  plannerTodayButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 11,
  },
  plannerTodayButtonActive: { backgroundColor: accent, borderColor: accent },
  plannerDesktopTodayButton: {
    backgroundColor: accentFaint,
    borderColor: accentBorder,
    minHeight: 26,
    paddingHorizontal: 14,
  },
  plannerTodayText: { color: muted, fontSize: 12 },
  plannerTodayTextActive: { color: panel, fontWeight: '700' },
  plannerDateArrowButton: {
    alignItems: 'center',
    backgroundColor: '#171817',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    width: 40,
  },
  plannerDesktopDateArrowButton: {
    height: 36,
    minHeight: 36,
    flexShrink: 0,
    width: 36,
  },
  plannerDateButton: {
    alignItems: 'center',
    backgroundColor: '#171817',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  plannerDesktopDateButton: {
    flex: 1,
    flexShrink: 1,
    justifyContent: 'center',
    minWidth: 220,
    minHeight: 36,
  },
  plannerDateText: { color: text, fontSize: 14, lineHeight: 19, textAlign: 'center' },
  plannerQuickAdd: {
    backgroundColor: '#171817',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 6,
    padding: 12,
  },
  plannerQuickAddButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  plannerQuickAddButtonDisabled: { opacity: 0.35 },
  plannerQuickDateButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 7,
    minHeight: 26,
    paddingHorizontal: 2,
  },
  plannerInlineAddButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 6,
    minHeight: 28,
    paddingHorizontal: 2,
  },
  plannerInlineAddText: { color: muted, fontSize: 12, lineHeight: 16 },
  plannerMonthView: { gap: 12 },
  plannerMobileMonthView: { gap: 10, paddingTop: 2 },
  plannerDesktopMonthView: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 18,
  },
  plannerDesktopMonthCalendar: {
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  plannerDesktopMonthSelectedList: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    flexShrink: 0,
    gap: 10,
    padding: 12,
    width: 340,
  },
  plannerMonthToolbar: { alignItems: 'flex-end', flexDirection: 'row', justifyContent: 'space-between' },
  plannerMobileMonthToolbar: { alignItems: 'flex-start', justifyContent: 'flex-start', marginTop: 8 },
  plannerMobileMonthGestureArea: {
    overflow: 'hidden',
    touchAction: 'none',
    width: '100%',
  },
  plannerMobileMonthPane: { width: '100%' },
  plannerMobileMonthPaneLayer: {
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  plannerMobileMonthTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
  },
  plannerMobileMonthBackButton: {
    alignItems: 'center',
    backgroundColor: '#1b1b1b',
    borderColor: '#2b2b2b',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  plannerMobileMonthBackText: { color: text, fontSize: 18, fontWeight: '700', lineHeight: 24 },
  plannerMonthNavButton: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  plannerMobileMonthNavButton: {
    backgroundColor: '#1b1b1b',
    borderColor: '#2b2b2b',
    height: 44,
    width: 44,
  },
  plannerMonthTitleBlock: { alignItems: 'center', gap: 1 },
  plannerMonthYear: { color: muted, fontSize: 10, lineHeight: 13 },
  plannerMonthTitle: { color: text, fontSize: 34, fontWeight: '800', lineHeight: 39 },
  plannerMobileMonthYear: { fontSize: 10, lineHeight: 13 },
  plannerMobileMonthTitle: { fontSize: 32, fontWeight: '900', lineHeight: 37, textAlign: 'left' },
  plannerMonthWeekHeader: {
    borderBottomColor: line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingBottom: 6,
  },
  plannerMobileMonthWeekHeader: { borderBottomColor: '#252525', paddingBottom: 6 },
  plannerMonthWeekText: { color: muted, flex: 1, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  plannerMobileMonthWeekText: { fontSize: 12, lineHeight: 16 },
  plannerMonthGrid: { borderBottomColor: '#242524', borderBottomWidth: 1 },
  plannerMobileMonthGrid: { borderBottomColor: '#202020' },
  plannerMonthWeekRow: { borderTopColor: line, borderTopWidth: 1, flexDirection: 'row' },
  plannerMobileMonthWeekRow: { borderTopColor: '#202020' },
  plannerMonthDayCell: {
    alignItems: 'stretch',
    flex: 1,
    gap: 4,
    minHeight: 82,
    paddingHorizontal: 3,
    paddingTop: 7,
  },
  plannerMobileMonthDayCell: {
    alignItems: 'center',
    gap: 3,
    minHeight: 54,
    paddingHorizontal: 1,
    paddingTop: 7,
  },
  plannerMonthDayCellMoveTarget: {
    backgroundColor: accentFaint,
    borderColor: accentBorder,
    borderRadius: 8,
    borderWidth: 1,
  },
  plannerMonthDayNumberWrap: {
    alignItems: 'center',
    borderRadius: 999,
    alignSelf: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  plannerMobileMonthDayNumberWrap: { height: 30, width: 30 },
  plannerMonthDayNumberToday: { borderColor: accent, borderWidth: 1 },
  plannerMonthDayNumberSelected: { backgroundColor: accent },
  plannerMonthDayNumber: { color: text, fontSize: 17, fontWeight: '700', lineHeight: 21 },
  plannerMobileMonthDayNumber: { fontSize: 19, fontWeight: '800', lineHeight: 24 },
  plannerMonthDayNumberSelectedText: { color: panel },
  plannerMonthTasks: { alignItems: 'stretch', gap: 2, minHeight: 50, width: '100%' },
  plannerMobileMonthTasks: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 3, justifyContent: 'center', minHeight: 12 },
  plannerMonthTaskChip: {
    backgroundColor: accentSoft,
    borderLeftColor: accent,
    borderLeftWidth: 3,
    borderRadius: 3,
    minHeight: 14,
    paddingHorizontal: 3,
    touchAction: 'pan-y',
    userSelect: 'none',
  },
  plannerMobileMonthTaskBar: {
    backgroundColor: accent,
    borderLeftWidth: 0,
    borderRadius: 999,
    height: 5,
    minHeight: 5,
    paddingHorizontal: 0,
    width: 19,
  },
  plannerMobileMonthTaskDot: {
    backgroundColor: accent,
    borderLeftWidth: 0,
    borderRadius: 999,
    height: 5,
    minHeight: 5,
    paddingHorizontal: 0,
    width: 5,
  },
  plannerMonthTaskChipDone: {
    backgroundColor: 'rgba(148, 148, 148, 0.08)',
    borderLeftColor: muted,
  },
  plannerMonthTaskChipMoving: {
    backgroundColor: accent,
    borderLeftColor: text,
  },
  plannerMonthTaskText: { color: text, fontSize: 9.5, lineHeight: 12 },
  plannerMonthMoreText: { color: accent, fontSize: 10, lineHeight: 12, paddingLeft: 4 },
  plannerMobileMonthMoreText: { color: muted, fontSize: 9, lineHeight: 10, paddingLeft: 0 },
  plannerMonthMoveHint: {
    alignItems: 'center',
    borderColor: '#3a2a1f',
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 34,
    paddingHorizontal: 10,
  },
  plannerMonthMoveHintText: { color: accent, fontSize: 12, lineHeight: 16 },
  plannerMonthMoveCancel: { minHeight: 28, justifyContent: 'center' },
  plannerMonthSelectedList: { gap: 8 },
  plannerMobileMonthSelectedList: { gap: 0, paddingHorizontal: 8, paddingTop: 0 },
  plannerMobileMonthSelectedHeader: { borderBottomColor: '#202020', borderBottomWidth: 1, minHeight: 36 },
  plannerMobileMonthSelectedTitle: { fontSize: 20, fontWeight: '800', lineHeight: 25 },
  plannerMonthEventRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 34,
    touchAction: 'pan-y',
    userSelect: 'none',
  },
  plannerMobileMonthEventRow: {
    borderBottomColor: '#202020',
    borderBottomWidth: 1,
    gap: 9,
    minHeight: 48,
    paddingVertical: 7,
  },
  plannerMonthEventRowMoving: { backgroundColor: accentFaint, borderRadius: 7, paddingHorizontal: 6 },
  plannerMonthEventIcon: { backgroundColor: accent, borderRadius: 999, height: 16, width: 16 },
  plannerMonthEventTitle: { color: text, flex: 1, fontSize: 14, lineHeight: 19 },
  plannerMobileMonthEventMark: { backgroundColor: accent, borderColor: accent, height: 17, width: 17 },
  plannerMobileMonthEventTitle: { fontSize: 17, fontWeight: '700', lineHeight: 22 },
  plannerMobileMonthEventTime: { color: text, fontSize: 15, lineHeight: 20 },
  plannerCalendarPanel: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  plannerCalendarPanelCompact: {
    gap: 8,
    padding: 8,
  },
  plannerCalendarPopover: {
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 30,
  },
  plannerCalendarScrim: {
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 25,
  },
  plannerCalendarGrid: { gap: 5 },
  plannerCalendarWeek: { flexDirection: 'row', justifyContent: 'space-between' },
  plannerCalendarGridCompact: { gap: 5 },
  plannerCalendarWeekTextCompact: { width: 36 },
  plannerCalendarDayBlank: { height: 38, width: 42 },
  plannerCalendarDayBlankCompact: { height: 31, width: 36 },
  plannerCalendarDay: {
    alignItems: 'center',
    backgroundColor: '#151615',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 42,
  },
  plannerCalendarDayCompact: {
    height: 31,
    width: 36,
  },
  plannerCalendarDayActive: { backgroundColor: accent, borderColor: accent },
  plannerCalendarDayText: { color: muted, fontSize: 12 },
  plannerCalendarDayTextActive: { color: panel, fontWeight: '700' },
  plannerCalendarDot: { backgroundColor: accent, borderRadius: 999, height: 4, marginTop: 3, width: 4 },
  plannerCalendarDotActive: { backgroundColor: panel },
  plannerTimelineHeader: { paddingTop: 2 },
  plannerDayTitle: { color: text, fontSize: 24, lineHeight: 30 },
  plannerDesktopTaskGroups: { gap: 12 },
  plannerDesktopTaskCard: {
    backgroundColor: '#171817',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 16px 36px rgba(0, 0, 0, 0.18)',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  plannerDesktopTaskCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  plannerDesktopTaskCardTitleGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  plannerDesktopTaskCardTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  plannerDesktopTaskBadge: {
    color: muted,
    fontSize: 12,
    fontVariant: ['tabular-nums'],
    lineHeight: 16,
  },
  plannerTimeline: { gap: 10 },
  plannerTimelineDesktop: {
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    borderTopWidth: 1,
    gap: 0,
  },
  plannerTimelineItem: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 9,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  plannerTimelineItemDesktop: {
    backgroundColor: 'transparent',
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    borderBottomWidth: 1,
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  plannerTimelineItemDesktopLast: {
    borderBottomWidth: 0,
  },
  plannerTimelineRowInner: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    minHeight: 30,
  },
  plannerTimelineRow: {
    alignItems: 'center',
    backgroundColor: '#171817',
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 30,
    paddingHorizontal: 9,
  },
  plannerTimelineRowDone: { opacity: 0.68 },
  plannerCompletedFirstRow: { marginTop: 5 },
  plannerTimelineCheckArea: { alignItems: 'center', flexDirection: 'row', gap: 7, minHeight: 30 },
  plannerTitleArea: { flex: 1, justifyContent: 'center', minHeight: 30, minWidth: 0 },
  plannerTime: { color: accent, fontSize: 12, fontVariant: ['tabular-nums'], lineHeight: 16, width: 44 },
  plannerTitle: { color: text, flexShrink: 1, fontSize: 14, lineHeight: 19 },
  plannerRowActions: { alignItems: 'center', flexDirection: 'row', gap: 5 },
  plannerSubtaskArrowButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 18,
  },
  plannerSubtaskArrowSpacer: { width: 18 },
  plannerStatusMark: {
    alignItems: 'center',
    height: 22,
    justifyContent: 'center',
    opacity: 0.95,
    width: 18,
  },
  plannerSubtasksInputRow: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  plannerEditSubtasksBox: { gap: 7 },
  plannerEditSubtasksList: { gap: 5 },
  plannerEditSubtaskChip: {
    alignItems: 'center',
    backgroundColor: '#101110',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 32,
    paddingLeft: 9,
    paddingRight: 5,
  },
  plannerEditSubtaskText: { color: text, flex: 1, fontSize: 12, lineHeight: 16 },
  plannerEditSubtaskInput: { color: text, flex: 1, fontSize: 12, minHeight: 24, padding: 0 },
  plannerEditSubtaskRemove: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  plannerSubtaskList: {
    borderLeftColor: '#343534',
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    gap: 2,
    marginLeft: 96,
    marginRight: 44,
    paddingBottom: 2,
    paddingTop: 0,
  },
  plannerSubtaskRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 24,
  },
  plannerSubtaskBranch: {
    borderTopColor: '#343534',
    borderTopWidth: 1,
    borderStyle: 'dashed',
    height: 1,
    marginLeft: -1,
    width: 14,
  },
  plannerSubtaskCheck: {
    alignItems: 'center',
    borderColor: muted,
    borderRadius: 999,
    borderWidth: 1,
    height: 15,
    justifyContent: 'center',
    width: 15,
  },
  plannerSubtaskCheckDone: { backgroundColor: accent, borderColor: accent },
  plannerSubtaskStatusMark: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 16,
  },
  plannerSubtaskText: { color: text, flex: 1, fontSize: 11, lineHeight: 15 },
  plannerEditButton: {
    alignItems: 'center',
    borderColor: 'rgba(255, 255, 255, 0.14)',
    borderRadius: 999,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  plannerConfirmPopover: {
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    paddingHorizontal: 18,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 36,
  },
  plannerConfirmCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  plannerConfirmActions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' },
  plannerCancelButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  plannerCancelText: { color: text, fontSize: 12 },
  plannerDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#ff4d4f',
    borderRadius: 7,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  plannerDeleteText: { color: panel, fontSize: 12, fontWeight: '700' },
  plannerDangerButton: {
    alignItems: 'center',
    backgroundColor: '#ff4d4d',
    borderRadius: 7,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  plannerEditPopover: {
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 35,
  },
  plannerEditCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 9,
    maxHeight: '86%',
    padding: 10,
  },
  plannerEditCloseButton: {
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  plannerEmptyTimeline: {
    alignItems: 'center',
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 58,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  plannerFormRow: { flexDirection: 'row', gap: 8 },
  plannerDateTimeButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
  },
  plannerDateTimeText: { color: text, fontSize: 14 },
  plannerFormField: {
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  plannerFormFieldSmall: {
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    width: 106,
  },
  plannerInput: { color: text, fontSize: 14, minHeight: 24, padding: 0 },
  plannerTimePickerPanel: { borderTopColor: line, borderTopWidth: 1, gap: 8, paddingTop: 10 },
  plannerTimePickerRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  plannerTimePickerInput: {
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    color: text,
    fontSize: 18,
    minHeight: 38,
    textAlign: 'center',
    width: 48,
  },
  plannerTimePickerColon: { color: text, fontSize: 18 },
  plannerTimeClearButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
  },
  plannerPickerDoneButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 7,
    minHeight: 38,
    justifyContent: 'center',
  },
  plannerTaskInputRow: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  plannerTaskInput: { color: text, flex: 1, fontSize: 14, minHeight: 38, padding: 0 },
  goalTitle: { color: text, flex: 1, fontSize: 15, lineHeight: 21 },
  moreText: { color: text, letterSpacing: 2 },
  goalPercent: { color: text, fontSize: 24, fontWeight: '300' },
  goalActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  stepper: { flexDirection: 'row', gap: 8 },
  stepButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  stepText: { color: accent, fontSize: 16 },
  weekRow: { flexDirection: 'row', justifyContent: 'space-between' },
  dayPill: { alignItems: 'center', borderRadius: 999, height: 28, justifyContent: 'center', width: 28 },
  dayPillActive: { backgroundColor: accent },
  dayText: { color: muted, fontSize: 11 },
  dayTextActive: { color: panel },
  dotRow: { flexDirection: 'row', gap: 12, marginTop: 4 },
  habitWeekRow: { flexDirection: 'row', gap: 12, marginTop: 4 },
  habitWeekCell: { alignItems: 'center', gap: 6 },
  habitWeekDate: { color: muted, fontSize: 10, lineHeight: 12 },
  habitWeekDateDone: { color: accent },
  habitDot: { backgroundColor: '#313231', borderRadius: 999, height: 8, width: 8 },
  habitDotDone: { backgroundColor: accent },
  habitHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  habitInfo: { flex: 1, gap: 2 },
  habitActions: { flexDirection: 'row', gap: 6 },
  iconButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    maxWidth: 390,
    padding: 16,
    width: '100%',
  },
  historyModalCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    maxHeight: 460,
    maxWidth: 390,
    padding: 16,
    width: '100%',
  },
  historyPreviewModalCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    maxHeight: 520,
    maxWidth: 390,
    padding: 16,
    width: '100%',
  },
  modalHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  modalHeaderText: { gap: 2 },
  modalCloseButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  modalTitle: { color: text, fontSize: 20, lineHeight: 27, marginTop: 4 },
  modalFields: { gap: 8 },
  modalInput: {
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    color: text,
    fontSize: 14,
    minHeight: 40,
    paddingHorizontal: 10,
  },
  calendarToolbar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  calendarStepper: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    minHeight: 34,
    paddingHorizontal: 4,
  },
  calendarArrowButton: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  calendarPickerText: { color: text, fontSize: 12, minWidth: 58, textAlign: 'center' },
  calendarWeekRow: { flexDirection: 'row', justifyContent: 'space-between' },
  calendarWeekText: { color: muted, fontSize: 10, textAlign: 'center', width: 42 },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  calendarDay: {
    alignItems: 'center',
    backgroundColor: '#151615',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 42,
  },
  calendarDayDone: { backgroundColor: accent, borderColor: accent },
  calendarDayText: { color: muted, fontSize: 12 },
  calendarDayTextDone: { color: panel, fontWeight: '700' },
  modalActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  messageSuccess: { color: accent },
  deleteButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    minHeight: 36,
    paddingRight: 8,
  },
  deleteButtonText: { color: muted, fontSize: 12 },
  saveButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 7,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  saveButtonDisabled: { backgroundColor: '#3a2a20' },
  saveButtonText: { color: panel, fontSize: 12, fontWeight: '700' },
  notificationButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 7,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  notificationButtonDisabled: { backgroundColor: '#3a2a20' },
  notificationButtonText: { color: panel, fontSize: 12, fontWeight: '700' },
  addOptionsRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  calendarSyncRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  calendarSyncDot: { backgroundColor: muted, borderRadius: 999, height: 7, width: 7 },
  calendarSyncDotSynced: { backgroundColor: accent },
  calendarSyncDotError: { backgroundColor: '#ff4d4d' },
  globalQuickAddButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    bottom: 74,
    height: 48,
    justifyContent: 'center',
    position: 'absolute',
    right: 16,
    width: 48,
    zIndex: 20,
  },
  desktopGlobalQuickAddButton: {
    bottom: 28,
    height: 54,
    right: 32,
    width: 54,
  },
  quickAddModalCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    maxWidth: 390,
    padding: 16,
    width: '100%',
  },
  widgetFeedList: { gap: 8 },
  widgetFeedRow: {
    alignItems: 'center',
    borderBottomColor: '#202120',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 34,
    paddingBottom: 7,
  },
  widgetFeedTime: { color: accent, fontSize: 11, minWidth: 82 },
  widgetFeedTitle: { color: text, flex: 1, fontSize: 13 },
  historyList: { gap: 8, paddingTop: 2 },
  historyRow: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 44,
    paddingHorizontal: 10,
  },
  historyRowActive: { backgroundColor: accent, borderColor: accent },
  historyDate: { color: muted, fontSize: 11, width: 54 },
  historyTime: { color: text, fontSize: 12, width: 42 },
  historyPreview: { color: text, flex: 1, fontSize: 12 },
  historyTextActive: { color: panel },
  historyPreviewContent: { gap: 14, paddingVertical: 2 },
  historyPreviewText: { color: text, fontSize: 14, lineHeight: 21, marginTop: 7 },
  historyPreviewStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  historyPreviewStat: {
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    flexGrow: 1,
    minWidth: 92,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  historyPreviewMeta: { color: text, fontSize: 13, lineHeight: 20, marginTop: 7 },
  profileStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  profileMetric: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 8,
    minHeight: 86,
    padding: 10,
    width: '48.8%',
  },
  profileMetricEmpty: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
  },
  profileMetricValueRow: { alignItems: 'center', flexDirection: 'row', gap: 7, minHeight: 38 },
  profileMetricInput: {
    color: text,
    flexShrink: 1,
    fontSize: 22,
    fontWeight: '300',
    minWidth: 44,
    padding: 0,
  },
  profileGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  profileEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  profileInput: {
    color: text,
    fontSize: 15,
    lineHeight: 21,
    minHeight: 38,
    padding: 0,
  },
  profileHeroInput: {
    fontSize: 21,
    fontWeight: '300',
    lineHeight: 28,
    minHeight: 46,
  },
  profileTextArea: {
    minHeight: 74,
  },
  profileHabitList: { gap: 12 },
  profileHabitRow: {
    alignItems: 'center',
    borderBottomColor: '#202120',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingBottom: 10,
  },
  profileHabitMark: {
    alignItems: 'center',
    borderColor: accent,
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  profileHabitText: { flex: 1, gap: 2, minWidth: 88 },
  profileHabitDays: { flexDirection: 'row', gap: 8 },
  textArea: {
    color: text,
    fontSize: 14,
    lineHeight: 20,
    minHeight: 72,
    padding: 0,
    textAlignVertical: 'top',
  },
  largeTextArea: {
    color: text,
    fontSize: 15,
    lineHeight: 22,
    minHeight: 170,
    padding: 0,
    textAlignVertical: 'top',
  },
  eveningSummaryList: { gap: 10 },
  eveningSummaryRow: { gap: 4 },
  cardLabelRow: { alignItems: 'center', flexDirection: 'row', gap: 6 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  metric: { minWidth: 92 },
  metricValue: { color: text, fontSize: 16, marginTop: 4 },
  sleepChipRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 8 },
  sleepInputChip: {
    borderBottomColor: line,
    borderBottomWidth: 1,
    flex: 1,
    minHeight: 36,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 6,
  },
  sleepInfoChip: {
    borderBottomColor: line,
    borderBottomWidth: 1,
    flex: 1.2,
    minHeight: 36,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 6,
  },
  sleepValue: { color: text, fontSize: 15, lineHeight: 19 },
  sleepPickerCard: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    maxWidth: 320,
    padding: 16,
    width: '86%',
  },
  sleepWheel: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    position: 'relative',
  },
  sleepWheelColumnShell: {
    flexGrow: 0,
    height: 184,
    overflow: 'hidden',
    position: 'relative',
    width: 92,
  },
  sleepWheelColumn: { height: 184, width: 92 },
  sleepWheelColumnContent: { gap: 4, paddingVertical: 75 },
  sleepWheelSelection: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 999,
    height: 34,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 75,
    zIndex: 0,
  },
  sleepWheelItem: {
    alignItems: 'center',
    borderRadius: 7,
    height: 34,
    justifyContent: 'center',
    marginHorizontal: 6,
  },
  sleepWheelText: { color: text, fontSize: 18, fontVariant: ['tabular-nums'], lineHeight: 24 },
  sleepWheelColon: { color: text, fontSize: 30, lineHeight: 34, zIndex: 1 },
  tagGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  tagChip: {
    alignItems: 'center',
    borderBottomColor: line,
    borderBottomWidth: 1,
    minHeight: 26,
    paddingHorizontal: 0,
    paddingVertical: 3,
  },
  tagChipActive: { borderBottomColor: accent },
  tagText: { color: muted, fontSize: 12 },
  tagTextActive: { color: accent },
  moodRow: { flexDirection: 'row', gap: 10 },
  moodButton: {
    alignItems: 'center',
    borderColor: line,
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  moodButtonActive: { backgroundColor: accent, borderColor: accent },
  moodText: { color: muted, fontSize: 12 },
  moodTextActive: { color: panel },
  kodaScreen: { flex: 1 },
  kodaDesktopWorkspace: { flex: 1, gap: 16, minHeight: 0 },
  assistantDesktopSurface: { flex: 1, gap: 16, height: 'calc(100vh - 56px)' as never, minHeight: 560, minWidth: 0, width: '100%' },
  kodaDesktopHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  assistantRightColumn: { gap: 12, paddingTop: 4 },
  kodaChatPane: {
    flex: 1,
    minHeight: 0,
  },
  kodaChatPaneDesktop: {
    backgroundColor: '#0f100f',
    borderColor: line,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'space-between',
    minWidth: 0,
    overflow: 'hidden',
  },
  chatList: { gap: 10, paddingBottom: 12 },
  chatListDesktop: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
  },
  chatBubble: {
    backgroundColor: panelSoft,
    borderColor: line,
    borderRadius: 7,
    borderWidth: 1,
    padding: 12,
  },
  chatBubbleDesktop: {
    maxWidth: 720,
  },
  chatBubbleUser: { borderColor: accentBorder },
  chatText: { color: text, fontSize: 14, lineHeight: 21 },
  chatInputRow: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#191a19',
    borderColor: line,
    borderRadius: 10,
    borderWidth: 1,
    boxShadow: '0 14px 34px rgba(0, 0, 0, 0.32)',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 18,
    maxWidth: 760,
    paddingHorizontal: 10,
    width: '100%',
  },
  chatInput: { color: text, flex: 1, fontSize: 14, minHeight: 46 },
  sendButton: { alignItems: 'center', height: 34, justifyContent: 'center', width: 34 },
  nav: {
    backgroundColor: panel,
    borderTopColor: line,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 13,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  mobileDrawerOverlay: { flex: 1, flexDirection: 'row' },
  mobileDrawerScrim: { backgroundColor: 'rgba(0,0,0,0.72)', bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  mobileDrawer: { backgroundColor: panel, borderRightColor: line, borderRightWidth: 1, flex: 1, maxWidth: 320, paddingBottom: 22, paddingHorizontal: 14, paddingTop: 16, shadowColor: '#000', shadowOffset: { height: 0, width: 12 }, shadowOpacity: 0.45, shadowRadius: 30, zIndex: 1 },
  mobileDrawerHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 22, minHeight: 42 },
  mobileDrawerClose: { alignItems: 'center', borderColor: line, borderRadius: 999, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  mobileDrawerNavigation: { gap: 5 },
  mobileDrawerItem: { alignItems: 'center', borderColor: 'transparent', borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 12, minHeight: 48, paddingHorizontal: 12 },
  mobileDrawerItemActive: { backgroundColor: accentFaint, borderColor: accentBorder },
  mobileDrawerIcon: { alignItems: 'center', justifyContent: 'center', width: 24 },
  mobileDrawerText: { color: muted, fontSize: 14, lineHeight: 19 },
  mobileDrawerTextActive: { color: accent, fontWeight: '700' },
  mobileDrawerFooter: { alignItems: 'center', borderTopColor: line, borderTopWidth: 1, flexDirection: 'row', gap: 8, marginTop: 'auto', paddingHorizontal: 10, paddingTop: 16 },
  navItem: { alignItems: 'center', flex: 1, gap: 3, minHeight: 42 },
  navItemFeatured: { gap: 0, minHeight: 48, transform: [{ translateY: -4 }] },
  navItemFeaturedActive: {},
  navFeaturedIcon: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 36,
  },
  navKMark: {
    color: accent,
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 29,
    opacity: 0.72,
    textShadowColor: accentGlow,
    textShadowOffset: { height: 0, width: 0 },
    textShadowRadius: 7,
  },
  navKMarkActive: {
    color: accent,
    opacity: 1,
    textShadowColor: accentGlow,
    textShadowRadius: 11,
  },
  navText: { color: muted, fontSize: 9 },
  navTextFeatured: { color: accent, fontSize: 10, fontWeight: '700', opacity: 0.72 },
  navTextFeaturedActive: { color: accent },
  navTextActive: { color: accent },
});
