import { Platform, StyleSheet } from 'react-native';
import type { KodaTheme } from '../theme/theme';

export const layoutStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  stage: {
    alignItems: 'center',
    flex: 1,
  },
  appFrame: {
    flex: 1,
    width: '100%',
    ...Platform.select({
      web: { maxWidth: 430 },
    }),
  },
  screenContent: {
    flexGrow: 1,
    paddingBottom: 22,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  heroBlock: { marginBottom: 20 },
  questionScreen: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  questionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  progressFill: {
    borderRadius: 999,
    height: 7,
  },
  questionContent: {
    flexGrow: 1,
    paddingBottom: 16,
    paddingTop: 32,
  },
  bottomAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 18,
    paddingTop: 10,
  },
  reviewHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  goalList: {
    gap: 10,
    marginBottom: 16,
    marginTop: 16,
  },
  goalBody: {
    flex: 1,
    gap: 4,
  },
  readyScreen: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 22,
  },
  readyMark: {
    alignItems: 'center',
    borderRadius: 8,
    height: 64,
    justifyContent: 'center',
    marginBottom: 22,
    width: 64,
  },
  centerText: { textAlign: 'center' },
});

export function makeThemedStyles(theme: KodaTheme) {
  return StyleSheet.create({
    kicker: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    title: {
      color: theme.text,
      fontSize: 30,
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 34,
      marginBottom: 10,
    },
    subtitle: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 22,
    },
    subtitleCenter: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 22,
      textAlign: 'center',
    },
    formCard: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 9,
      marginBottom: 14,
      padding: 16,
    },
    methodCard: {
      backgroundColor: theme.accentSoft,
      borderRadius: 8,
      marginBottom: 16,
      padding: 14,
    },
    methodTitle: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '900',
      marginBottom: 5,
    },
    methodText: {
      color: theme.label,
      fontSize: 13,
      lineHeight: 19,
    },
    label: {
      color: theme.label,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 2,
    },
    input: {
      backgroundColor: theme.surfaceSoft,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      color: theme.text,
      fontSize: 16,
      minHeight: 48,
      paddingHorizontal: 13,
    },
    iconButton: {
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    progressText: {
      color: theme.text,
      fontSize: 17,
      fontWeight: '800',
    },
    progressTrack: {
      backgroundColor: theme.surfaceSoft,
      borderRadius: 999,
      height: 7,
      overflow: 'hidden',
    },
    aiBadge: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: theme.accentSoft,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 8,
      marginBottom: 18,
      paddingHorizontal: 11,
      paddingVertical: 8,
    },
    aiBadgeText: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: '800',
    },
    questionEyebrow: {
      color: theme.muted,
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    questionTitle: {
      color: theme.text,
      fontSize: 25,
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 30,
      marginBottom: 10,
    },
    rationale: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 16,
    },
    textArea: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      color: theme.text,
      fontSize: 16,
      lineHeight: 23,
      minHeight: 150,
      padding: 14,
    },
    stepCounter: {
      color: theme.muted,
      fontSize: 14,
      fontWeight: '700',
      minWidth: 52,
    },
    reviewIcon: {
      alignItems: 'center',
      backgroundColor: theme.accentSoft,
      borderRadius: 8,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    profileCard: {
      backgroundColor: theme.accentSoft,
      borderRadius: 8,
      marginTop: 16,
      padding: 15,
    },
    profileLabel: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: '900',
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    profileTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: 6,
    },
    profileText: {
      color: theme.label,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 8,
    },
    profileStrategy: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '800',
      lineHeight: 20,
    },
    goalCard: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 11,
      padding: 13,
    },
    goalNumber: {
      alignItems: 'center',
      backgroundColor: theme.accentSoft,
      borderRadius: 8,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    goalNumberText: {
      color: theme.accent,
      fontSize: 14,
      fontWeight: '900',
    },
    goalTitle: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '800',
    },
    goalTarget: {
      color: theme.label,
      fontSize: 14,
      lineHeight: 20,
    },
    goalStep: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 19,
      marginTop: 3,
    },
    nextStepCard: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      marginBottom: 16,
      padding: 16,
      width: '100%',
    },
    nextStepLabel: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: '900',
      marginBottom: 7,
      textTransform: 'uppercase',
    },
    nextStepTitle: {
      color: theme.text,
      fontSize: 20,
      fontWeight: '800',
      lineHeight: 25,
      marginBottom: 4,
    },
    nextStepReward: {
      color: theme.muted,
      fontSize: 15,
      fontWeight: '700',
    },
    secondaryButton: {
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 50,
      paddingHorizontal: 18,
      width: '100%',
    },
    secondaryButtonText: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '800',
    },
  });
}
