import assert from 'node:assert/strict';
import { advanceTimer, initialTimer, restoreTimer } from '../src/features/koda/pomodoroTimer';
import { defaultPomodoroSettings as settings } from '../src/features/koda/persistence';
const now = 1_800_000_000_000;
const start = { ...initialTimer(settings), status: 'running' as const, endsAt: now + settings.workMinutes * 60000 };
assert.equal(advanceTimer(start, settings, now + 65000).remainingSeconds, settings.workMinutes * 60 - 65);
const restored = restoreTimer(JSON.stringify(start), settings);
assert.equal(advanceTimer(restored, settings, now + 65000).remainingSeconds, settings.workMinutes * 60 - 65);
const breakState = advanceTimer(start, settings, start.endsAt + 30000);
assert.equal(breakState.mode, 'break');
assert.equal(breakState.completedWorkSessions, 1);
assert.equal(breakState.remainingSeconds, settings.breakMinutes * 60 - 30);
const paused = { ...breakState, status: 'paused' as const, endsAt: null };
assert.deepEqual(advanceTimer(paused, settings, now + 86400000), paused);
assert.deepEqual(restoreTimer(JSON.stringify(paused), settings), paused);
const daysLater = advanceTimer(start, settings, now + 7 * 86400000);
assert(daysLater.endsAt! > now + 7 * 86400000);
assert(daysLater.completedWorkSessions > 1);
assert.deepEqual(restoreTimer('broken', settings), initialTimer(settings));
const atBoundary = advanceTimer(start, settings, start.endsAt);
assert.deepEqual(advanceTimer(atBoundary, settings, start.endsAt), atBoundary);
console.log('Timer: background time, reload, pause, phase transition, long suspension and exact boundary PASS');
